const professions = [
  "teacher",
  "doctor",
  "police officer",
  "chef / cook",
  "firefighter",
  "bus driver",
  "scientist",
  "post man",
  "vet",
  "artist",
  "pilot",
  "nurse",
  "baker",
  "builder",
  "judge",
  "farmer",
  "waiter",
  "waitress",
  "butcher",
  "cashier",
  "astronaut",
  "football player",
  "car mechanic",
  "flight attendant",
  "musician",
  "taxi driver",
  "barber",
  "hairdresser",
  "pharmacist",
  "business man",
  "office worker",
  "maid",
  "tour guide",
  "soldier",
  "sailor",
  "fighter pilot",
  "miner",
  "plumber",
  "photographer",
  "reporter",
  "make up artist",
  "director",
  "computer programmer",
  "architect",
  "optician",
  "surgeon",
  "astronomer",
  "professional golf player",
  "detective",
];

export default professions;
